# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'first.ui'
#
# Created: Wed Feb 18 23:37:31 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(900, 640)
        Form.setStyleSheet(_fromUtf8(""))
        self.horizontalLayout = QtGui.QHBoxLayout(Form)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.verticalLayout_2.setContentsMargins(-1, -1, 0, -1)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        spacerItem = QtGui.QSpacerItem(20, 32, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem)
        self.importButton = QtGui.QPushButton(Form)
        self.importButton.setObjectName(_fromUtf8("importButton"))
        self.verticalLayout_2.addWidget(self.importButton)
        self.stockButton = QtGui.QPushButton(Form)
        self.stockButton.setObjectName(_fromUtf8("stockButton"))
        self.verticalLayout_2.addWidget(self.stockButton)
        self.separateButton = QtGui.QPushButton(Form)
        self.separateButton.setObjectName(_fromUtf8("separateButton"))
        self.verticalLayout_2.addWidget(self.separateButton)
        self.checkMButton = QtGui.QPushButton(Form)
        self.checkMButton.setObjectName(_fromUtf8("checkMButton"))
        self.verticalLayout_2.addWidget(self.checkMButton)
        self.recognitionButton = QtGui.QPushButton(Form)
        self.recognitionButton.setObjectName(_fromUtf8("recognitionButton"))
        self.verticalLayout_2.addWidget(self.recognitionButton)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.verticalLayout_2.setStretch(3, 1)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.tabWidget_2 = QtGui.QTabWidget(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget_2.sizePolicy().hasHeightForWidth())
        self.tabWidget_2.setSizePolicy(sizePolicy)
        self.tabWidget_2.setMinimumSize(QtCore.QSize(0, 0))
        self.tabWidget_2.setObjectName(_fromUtf8("tabWidget_2"))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.tab_4)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.view3d = QtGui.QFrame(self.tab_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.view3d.sizePolicy().hasHeightForWidth())
        self.view3d.setSizePolicy(sizePolicy)
        self.view3d.setMinimumSize(QtCore.QSize(0, 300))
        self.view3d.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.view3d.setFrameShape(QtGui.QFrame.StyledPanel)
        self.view3d.setFrameShadow(QtGui.QFrame.Raised)
        self.view3d.setObjectName(_fromUtf8("view3d"))
        self.verticalLayout_5.addWidget(self.view3d)
        self.tabWidget_2.addTab(self.tab_4, _fromUtf8(""))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.verticalLayout = QtGui.QVBoxLayout(self.tab_5)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.stepText = QtGui.QTextEdit(self.tab_5)
        self.stepText.setReadOnly(True)
        self.stepText.setObjectName(_fromUtf8("stepText"))
        self.verticalLayout.addWidget(self.stepText)
        self.tabWidget_2.addTab(self.tab_5, _fromUtf8(""))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.gtdText = QtGui.QTextEdit(self.tab)
        self.gtdText.setObjectName(_fromUtf8("gtdText"))
        self.verticalLayout_3.addWidget(self.gtdText)
        self.tabWidget_2.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.tab_2)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.stockView = QtGui.QFrame(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stockView.sizePolicy().hasHeightForWidth())
        self.stockView.setSizePolicy(sizePolicy)
        self.stockView.setMinimumSize(QtCore.QSize(0, 300))
        self.stockView.setFrameShape(QtGui.QFrame.StyledPanel)
        self.stockView.setFrameShadow(QtGui.QFrame.Raised)
        self.stockView.setObjectName(_fromUtf8("stockView"))
        self.verticalLayout_6.addWidget(self.stockView)
        self.stockSD = QtGui.QLabel(self.tab_2)
        self.stockSD.setAlignment(QtCore.Qt.AlignCenter)
        self.stockSD.setObjectName(_fromUtf8("stockSD"))
        self.verticalLayout_6.addWidget(self.stockSD)
        self.stockSL = QtGui.QLabel(self.tab_2)
        self.stockSL.setAlignment(QtCore.Qt.AlignCenter)
        self.stockSL.setObjectName(_fromUtf8("stockSL"))
        self.verticalLayout_6.addWidget(self.stockSL)
        self.tabWidget_2.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.tab_3)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.deltaView = QtGui.QFrame(self.tab_3)
        self.deltaView.setFrameShape(QtGui.QFrame.StyledPanel)
        self.deltaView.setFrameShadow(QtGui.QFrame.Raised)
        self.deltaView.setObjectName(_fromUtf8("deltaView"))
        self.verticalLayout_7.addWidget(self.deltaView)
        self.tabWidget_2.addTab(self.tab_3, _fromUtf8(""))
        self.verticalLayout_4.addWidget(self.tabWidget_2)
        self.treeWidget = QtGui.QTreeWidget(Form)
        self.treeWidget.setObjectName(_fromUtf8("treeWidget"))
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget)
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_2 = QtGui.QTreeWidgetItem(item_1)
        item_3 = QtGui.QTreeWidgetItem(item_2)
        item_3 = QtGui.QTreeWidgetItem(item_2)
        item_3 = QtGui.QTreeWidgetItem(item_2)
        item_3 = QtGui.QTreeWidgetItem(item_2)
        item_3 = QtGui.QTreeWidgetItem(item_2)
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget)
        self.verticalLayout_4.addWidget(self.treeWidget)
        self.horizontalLayout.addLayout(self.verticalLayout_4)

        self.retranslateUi(Form)
        self.tabWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Form", None))
        self.importButton.setText(_translate("Form", "Import a part STEP file", None))
        self.stockButton.setText(_translate("Form", "Import a stock STEP file", None))
        self.separateButton.setText(_translate("Form", "Separate and print GTD", None))
        self.checkMButton.setText(_translate("Form", "Calculate DeltaVolume", None))
        self.recognitionButton.setText(_translate("Form", "Start recognition", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_4), _translate("Form", "3D View", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_5), _translate("Form", "STEP", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab), _translate("Form", "Geometric and Topological Data", None))
        self.stockSD.setText(_translate("Form", "Stock Diamater SD =", None))
        self.stockSL.setText(_translate("Form", "Stock Length SL =", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_2), _translate("Form", "Stock", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_3), _translate("Form", "DeltaVolume", None))
        self.treeWidget.headerItem().setText(0, _translate("Form", "1", None))
        self.treeWidget.headerItem().setText(1, _translate("Form", "New Column", None))
        self.treeWidget.headerItem().setText(2, _translate("Form", "New Column", None))
        __sortingEnabled = self.treeWidget.isSortingEnabled()
        self.treeWidget.setSortingEnabled(False)
        self.treeWidget.topLevelItem(0).setText(0, _translate("Form", "New Item", None))
        self.treeWidget.topLevelItem(1).setText(0, _translate("Form", "New Item", None))
        self.treeWidget.topLevelItem(1).child(0).setText(0, _translate("Form", "New Subitem", None))
        self.treeWidget.topLevelItem(1).child(0).child(0).setText(0, _translate("Form", "New Subitem", None))
        self.treeWidget.topLevelItem(1).child(0).child(0).child(0).setText(0, _translate("Form", "New Subitem", None))
        self.treeWidget.topLevelItem(1).child(0).child(0).child(1).setText(0, _translate("Form", "New Item", None))
        self.treeWidget.topLevelItem(1).child(0).child(0).child(1).setText(1, _translate("Form", "hgff", None))
        self.treeWidget.topLevelItem(1).child(0).child(0).child(2).setText(0, _translate("Form", "New Item", None))
        self.treeWidget.topLevelItem(1).child(0).child(0).child(2).setText(1, _translate("Form", "jyhrhgdfvd", None))
        self.treeWidget.topLevelItem(1).child(0).child(0).child(2).setText(2, _translate("Form", "gfedcscdz\"rez", None))
        self.treeWidget.topLevelItem(1).child(0).child(0).child(3).setText(0, _translate("Form", "New Item", None))
        self.treeWidget.topLevelItem(1).child(0).child(0).child(4).setText(0, _translate("Form", "New Item", None))
        self.treeWidget.topLevelItem(2).setText(0, _translate("Form", "New Item", None))
        self.treeWidget.setSortingEnabled(__sortingEnabled)

