
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = '\x9a\x89\xbe\xb6\xa1`\xe6\xfaE\xbf~\xebZ\xfb\x8a\xe8'
    
_lr_action_items = {'ENDSEC':([6,13,14,18,22,23,24,42,47,52,53,59,64,65,69,70,],[-42,21,-35,-32,-36,-34,-37,51,-31,-12,63,-30,-11,-4,-7,-6,]),'REAL':([17,20,32,46,50,66,],[27,27,27,27,27,27,]),',':([27,28,29,30,33,34,35,36,38,39,40,41,43,48,49,60,61,71,72,],[-19,-22,-17,46,-23,-21,-20,-25,-26,-18,-14,-24,46,46,-29,-13,-27,-28,46,]),'PART21_START':([0,],[2,]),'BINARY':([17,20,32,46,50,66,],[28,28,28,28,28,28,]),')':([17,27,28,29,30,32,33,34,35,36,38,39,40,41,43,48,49,60,61,62,66,67,68,71,72,73,75,76,],[31,-19,-22,-17,45,49,-23,-21,-20,-25,-26,-18,-14,-24,54,61,-29,-13,-27,71,73,74,-41,-28,76,-38,-40,-39,]),'(':([8,10,11,12,17,20,32,37,44,46,50,55,66,],[17,20,-15,-16,32,32,32,50,56,32,32,66,32,]),'*':([17,20,32,46,50,66,],[33,33,33,33,33,33,]),'ENTITY_INSTANCE_NAME':([6,13,14,17,18,20,22,23,24,32,46,47,50,59,66,69,70,],[-42,26,-35,35,-32,35,-36,-34,-37,35,35,-31,35,-30,35,-7,-6,]),'ENUMERATION':([17,20,32,46,50,66,],[34,34,34,34,34,34,]),'$':([17,20,32,46,50,66,],[41,41,41,41,41,41,]),'PART21_END':([5,7,15,21,],[-10,16,-9,-33,]),'STRING':([17,20,32,46,50,66,],[29,29,29,29,29,29,]),'USER_DEFINED_KEYWORD':([4,9,17,19,20,32,42,44,46,50,52,53,56,64,65,66,67,68,73,75,76,],[11,11,11,11,11,11,11,11,11,11,-12,11,11,-11,-4,11,11,-41,-38,-40,-39,]),'INTEGER':([17,20,32,46,50,66,],[39,39,39,39,39,39,]),';':([8,31,45,54,57,58,73,74,76,],[18,47,59,65,69,70,-38,-8,-39,]),'STANDARD_KEYWORD':([4,9,17,19,20,32,42,44,46,50,52,53,56,64,65,66,67,68,73,75,76,],[12,12,12,12,12,12,12,12,12,12,-12,12,12,-11,-4,12,12,-41,-38,-40,-39,]),'=':([25,26,],[44,-5,]),'$end':([1,16,],[0,-1,]),'DATA_SEC':([3,5,7,15,21,51,63,],[8,-10,8,-9,-33,-2,-3,]),'HEADER_SEC':([2,],[4,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'simple_entity_instance':([13,],[22,]),'header_entity':([4,9,19,42,53,],[9,19,42,52,64,]),'simple_record_list':([56,],[67,]),'header_section':([2,],[3,]),'keyword':([4,9,17,19,20,32,42,44,46,50,53,56,66,67,],[10,10,37,10,37,37,10,55,37,37,10,55,37,55,]),'complex_entity_instance':([13,],[24,]),'data_section':([3,7,],[5,15,]),'subsuper_record':([44,],[57,]),'check_entity_instance_name':([13,],[25,]),'entity_instance':([13,],[23,]),'list_parameter':([17,20,32,46,50,66,],[38,38,38,38,38,38,]),'data_start':([3,7,],[6,6,]),'typed_parameter':([17,20,32,46,50,66,],[36,36,36,36,36,36,]),'entity_instance_list':([6,],[13,]),'parameter_list':([17,20,32,66,],[30,43,48,72,]),'data_section_list':([3,],[7,]),'header_entity_list':([42,],[53,]),'parameter':([17,20,32,46,50,66,],[40,40,40,60,62,40,]),'exchange_file':([0,],[1,]),'empty':([6,],[14,]),'simple_record':([44,56,67,],[58,68,75,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> exchange_file","S'",1,None,None,None),
  ('exchange_file -> PART21_START header_section data_section_list PART21_END','exchange_file',4,'p_exchange_file','/usr/local/lib/python2.7/dist-packages/SCL/Part21.py',218),
  ('header_section -> HEADER_SEC header_entity header_entity header_entity ENDSEC','header_section',5,'p_header_section','/usr/local/lib/python2.7/dist-packages/SCL/Part21.py',223),
  ('header_section -> HEADER_SEC header_entity header_entity header_entity header_entity_list ENDSEC','header_section',6,'p_header_section_with_entity_list','/usr/local/lib/python2.7/dist-packages/SCL/Part21.py',227),
  ('header_entity -> keyword ( parameter_list ) ;','header_entity',5,'p_header_entity','/usr/local/lib/python2.7/dist-packages/SCL/Part21.py',232),
  ('check_entity_instance_name -> ENTITY_INSTANCE_NAME','check_entity_instance_name',1,'p_check_entity_instance_name','/usr/local/lib/python2.7/dist-packages/SCL/Part21.py',236),
  ('simple_entity_instance -> check_entity_instance_name = simple_record ;','simple_entity_instance',4,'p_simple_entity_instance','/usr/local/lib/python2.7/dist-packages/SCL/Part21.py',245),
  ('complex_entity_instance -> check_entity_instance_name = subsuper_record ;','complex_entity_instance',4,'p_complex_entity_instance','/usr/local/lib/python2.7/dist-packages/SCL/Part21.py',249),
  ('subsuper_record -> ( simple_record_list )','subsuper_record',3,'p_subsuper_record','/usr/local/lib/python2.7/dist-packages/SCL/Part21.py',253),
  ('data_section_list -> data_section_list data_section','data_section_list',2,'p_data_section_list','/usr/local/lib/python2.7/dist-packages/SCL/Part21.py',257),
  ('data_section_list -> data_section','data_section_list',1,'p_data_section_list','/usr/local/lib/python2.7/dist-packages/SCL/Part21.py',258),
  ('header_entity_list -> header_entity_list header_entity','header_entity_list',2,'p_header_entity_list','/usr/local/lib/python2.7/dist-packages/SCL/Part21.py',263),
  ('header_entity_list -> header_entity','header_entity_list',1,'p_header_entity_list','/usr/local/lib/python2.7/dist-packages/SCL/Part21.py',264),
  ('parameter_list -> parameter_list , parameter','parameter_list',3,'p_parameter_list','/usr/local/lib/python2.7/dist-packages/SCL/Part21.py',269),
  ('parameter_list -> parameter','parameter_list',1,'p_parameter_list','/usr/local/lib/python2.7/dist-packages/SCL/Part21.py',270),
  ('keyword -> USER_DEFINED_KEYWORD','keyword',1,'p_keyword','/usr/local/lib/python2.7/dist-packages/SCL/Part21.py',275),
  ('keyword -> STANDARD_KEYWORD','keyword',1,'p_keyword','/usr/local/lib/python2.7/dist-packages/SCL/Part21.py',276),
  ('parameter -> STRING','parameter',1,'p_parameter_simple','/usr/local/lib/python2.7/dist-packages/SCL/Part21.py',280),
  ('parameter -> INTEGER','parameter',1,'p_parameter_simple','/usr/local/lib/python2.7/dist-packages/SCL/Part21.py',281),
  ('parameter -> REAL','parameter',1,'p_parameter_simple','/usr/local/lib/python2.7/dist-packages/SCL/Part21.py',282),
  ('parameter -> ENTITY_INSTANCE_NAME','parameter',1,'p_parameter_simple','/usr/local/lib/python2.7/dist-packages/SCL/Part21.py',283),
  ('parameter -> ENUMERATION','parameter',1,'p_parameter_simple','/usr/local/lib/python2.7/dist-packages/SCL/Part21.py',284),
  ('parameter -> BINARY','parameter',1,'p_parameter_simple','/usr/local/lib/python2.7/dist-packages/SCL/Part21.py',285),
  ('parameter -> *','parameter',1,'p_parameter_simple','/usr/local/lib/python2.7/dist-packages/SCL/Part21.py',286),
  ('parameter -> $','parameter',1,'p_parameter_simple','/usr/local/lib/python2.7/dist-packages/SCL/Part21.py',287),
  ('parameter -> typed_parameter','parameter',1,'p_parameter_simple','/usr/local/lib/python2.7/dist-packages/SCL/Part21.py',288),
  ('parameter -> list_parameter','parameter',1,'p_parameter_simple','/usr/local/lib/python2.7/dist-packages/SCL/Part21.py',289),
  ('list_parameter -> ( parameter_list )','list_parameter',3,'p_list_parameter','/usr/local/lib/python2.7/dist-packages/SCL/Part21.py',293),
  ('typed_parameter -> keyword ( parameter )','typed_parameter',4,'p_typed_parameter','/usr/local/lib/python2.7/dist-packages/SCL/Part21.py',297),
  ('parameter -> ( )','parameter',2,'p_parameter_empty_list','/usr/local/lib/python2.7/dist-packages/SCL/Part21.py',301),
  ('data_start -> DATA_SEC ( parameter_list ) ;','data_start',5,'p_data_start','/usr/local/lib/python2.7/dist-packages/SCL/Part21.py',305),
  ('data_start -> DATA_SEC ( ) ;','data_start',4,'p_data_start_empty','/usr/local/lib/python2.7/dist-packages/SCL/Part21.py',309),
  ('data_start -> DATA_SEC ;','data_start',2,'p_data_start_empty','/usr/local/lib/python2.7/dist-packages/SCL/Part21.py',310),
  ('data_section -> data_start entity_instance_list ENDSEC','data_section',3,'p_data_section','/usr/local/lib/python2.7/dist-packages/SCL/Part21.py',314),
  ('entity_instance_list -> entity_instance_list entity_instance','entity_instance_list',2,'p_entity_instance_list','/usr/local/lib/python2.7/dist-packages/SCL/Part21.py',318),
  ('entity_instance_list -> empty','entity_instance_list',1,'p_entity_instance_list','/usr/local/lib/python2.7/dist-packages/SCL/Part21.py',319),
  ('entity_instance -> simple_entity_instance','entity_instance',1,'p_entity_instance','/usr/local/lib/python2.7/dist-packages/SCL/Part21.py',325),
  ('entity_instance -> complex_entity_instance','entity_instance',1,'p_entity_instance','/usr/local/lib/python2.7/dist-packages/SCL/Part21.py',326),
  ('simple_record -> keyword ( )','simple_record',3,'p_simple_record_empty','/usr/local/lib/python2.7/dist-packages/SCL/Part21.py',331),
  ('simple_record -> keyword ( parameter_list )','simple_record',4,'p_simple_record_with_params','/usr/local/lib/python2.7/dist-packages/SCL/Part21.py',335),
  ('simple_record_list -> simple_record_list simple_record','simple_record_list',2,'p_simple_record_list','/usr/local/lib/python2.7/dist-packages/SCL/Part21.py',339),
  ('simple_record_list -> simple_record','simple_record_list',1,'p_simple_record_list','/usr/local/lib/python2.7/dist-packages/SCL/Part21.py',340),
  ('empty -> <empty>','empty',0,'p_empty','/usr/local/lib/python2.7/dist-packages/SCL/Part21.py',345),
]
